export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const LOGGED_USER_SUCCESS = "LOGGED_USER_SUCCESS";
export const LOGGED_USER_FAIL = "LOGGED_USER_FAIL";

export const VERIFY_SUCCESS = "USER_DELETE_SUCCESS";
export const VERIFY_FAIL = "USER_DELETE_FAIL";

export const RECOVER_SUCCESS = "RECOVER_SUCCESS";
export const RECOVER_FAIL = "RECOVER_FAIL";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";

export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const SELLER_PRODUCTS = "SELLER_PRODUCTS";
export const USER_SINGLE_LOAD_SUCCESS = "USER_SINGLE_LOAD_SUCCESS";
export const USER_SINGLE_LOAD_FAIL = "USER_SINGLE_LOAD_FAIL";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS";
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL";

export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const CATEGORY_LOAD_SUCCESS = "CATEGORY_LOAD_SUCCESS";
export const CATEGORY_LOAD_FAIL = "CATEGORY_LOAD_FAIL";
export const CATEGORY_EMPTY_SET = "CATEGORY_EMPTY_SET";

export const CATEGORY_SINGLE_LOAD_SUCCESS = "CATEGORY_SINGLE_LOAD_SUCCESS";
export const CATEGORY_SINGLE_LOAD_FAIL = "CATEGORY_SINGLE_LOAD_FAIL";

export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS";
export const SUBCATEGORY_FAIL = "SUBCATEGORY_FAIL";

export const SUBCATEGORY_LOAD_SUCCESS = "SUBCATEGORY_LOAD_SUCCESS";
export const SUBCATEGORY_LOAD_FAIL = "SUBCATEGORY_LOAD_FAIL";
export const SUBCATEGORY_EMPTY_SET = "SUBCATEGORY_EMPTY_SET";

export const SUBCATEGORY_SINGLE_LOAD_SUCCESS = "UBCATEGORY_SINGLE_LOAD_SUCCESS";
export const SUBCATEGORY_SINGLE_LOAD_FAIL = "SUBCATEGORY_SINGLE_LOAD_FAIL";

export const SUBCATEGORY_UPDATE_SUCCESS = "SUBCATEGORY_UPDATE_SUCCESS";
export const SUBCATEGORY_UPDATE_FAIL = "SUBCATEGORY_UPDATE_FAIL";

export const SUBCATEGORY_DELETE_SUCCESS = "SUBCATEGORY_DELETE_SUCCESS";
export const SUBCATEGORY_DELETE_FAIL = "SUBCATEGORY_DELETE_FAIL";

export const TAG_SUCCESS = "TAG_SUCCESS";
export const TAG_FAIL = "TAG_FAIL";

export const TAG_UPDATE_SUCCESS = "TAG_UPDATE_SUCCESS";
export const TAG_UPDATE_FAIL = "TAG_UPDATE_FAIL";

export const TAG_DELETE_SUCCESS = "TAG_DELETE_SUCCESS";
export const TAG_DELETE_FAIL = "TAG_DELETE_FAIL";

export const TAG_LOAD_SUCCESS = "TAG_LOAD_SUCCESS";
export const TAG_LOAD_FAIL = "TAG_LOAD_FAIL";
export const TAG_EMPTY_SET = "TAG_EMPTY_SET";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAIL = "CAHNGE_EMAIL_FAIL";

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS";
export const PRODUCT_LOAD_FAIL = "PRODUCT_LOAD_FAIL";
export const PRODUCT_EMPTY_SET = "PRODUCT_EMPTY_SET";

export const PRODUCT_SINGLE_LOAD_SUCCESS = "PRODUCT_SINGLE_LOAD_SUCCESS";
export const PRODUCT_SINGLE_LOAD_FAIL = "PRODUCT_SINGLE_LOAD_FAIL";

export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_FAIL = "BRAND_FAIL";

export const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
export const BRAND_UPDATE_FAIL = "BRAND_UPDATE_FAIL";

export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
export const BRAND_DELETE_FAIL = "BRAND_DELETE_FAIL";

export const BRAND_LOAD_SUCCESS = "BRAND_LOAD_SUCCESS";
export const BRAND_LOAD_FAIL = "BRAND_LOAD_FAIL";
export const BRAND_EMPTY_SET = "BRAND_EMPTY_SET";

export const WISHLIST_SUCCESS = "WISHLIST_LOAD_SUCCESS";
export const WISHLIST_FAIL = "WISHLIST_LOAD_FAIL";

export const WISHLIST_DELETE_SUCCESS = "WISHLIST_DELETE_SUCCESS";
export const WISHLIST_DELETE_FAIL = "WISHLIST_DELETE_FAIL";

export const WISHLIST_LOAD_SUCCESS = "WISHLIST_LOAD_SUCCESS";
export const WISHLIST_LOAD_FAIL = "WISHLIST_LOAD_FAIL";

export const WISHLIST_SAVE_SUCCESS = "WISHLIST_SAVE_SUCCESS";
export const WISHLIST_SAVE_FAIL = "WISHLIST_SAVE_FAIL";

export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";

export const ORDER_LOAD_SUCCESS = "ORDER_LOAD_SUCCESS";
export const ORDER_LOAD_FAIL = "ORDER_LOAD_FAIL";

export const REVIEW_ADD_SUCCESS = "REVIEW_ADD_SUCCESS";
export const REVIEW_ADD_FAIL = "REVIEW_ADD_FAIL";

export const REVIEW_PRODUCT_SUCCESS = "REVIEW_LOAD_SUCCESS";
export const REVIEW_PRODUCT_FAIL = "REVIEW_LOAD_FAIL";

export const REVIEW_ORDER_COMPLETE_SUCCESS = "REVIEW_ORDER_COMPLETE_SUCCESS";
export const REVIEW_ORDER_COMPLETE_FAIL = "REVIEW_ORDER_COMPLETE_FAIL";

export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";

export const BANNER_LOAD_SUCCESS = "BANNER_LOAD_SUCESS";
export const BANNER_LOAD_FAIL = "BANNER_LOAD_FAIL";

export const BANNER_REMOVE_SUCCESS = "BANNER_REMOVE_SUCCESS";
export const BANNER_REMOVE_FAIL = "BANNER_REMOVE_SUCCESS";

export const ADD_VOUCHER_SUCCESS = "ADD_VOUCHER_SUCCESS";
export const ADD_VOUCHER_FAIL = "ADD_VOUCHER_FAIL";

export const LOAD_VOUCHERS_SUCCESS = "LOAD_VOUCHER_SUCCESS";
export const LOAD_VOUCHERS_FAIL = "LOAD_VOUCHER_FAIL";

export const GET_VOUCHER_SUCCESS = "GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_FAIL = "GET_VOUCHER_FAIL";

export const DELETE_VOUCHER_SUCCESS = "DELETE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_FAIL = "DELETE_VOUCHER_SUCCESS";

export const GET_SEARCHED_ITEMS = "searchedArr";

export const VALIDATE_VOUCHER_SUCCESS = "VALIDATE_VOUCHER_SUCCESS";
export const VALIDATE_VOUCHER_FAIL = "VALIDATE_VOUCHER_FAIL";
export const GET_BLOG = "GET_BLOG";
export const GET_SINGLE_BLOG = "GET_SINGLE_BLOG";

export const GET_ANALYTICS = "GET_ANALYTICS";
export const GET_PRODUCTS_BY_TAGS = "GET_PRODUCTS_BY_TAGS";
export const GET_ALL_DEALS = "GET_ALL_DEALS";
export const GET_POSTED_DEAL = "GET_POSTED_DEAL";
export const LOAD_SELLER_ANALYTICS_SUCCESS = "LOAD_SELLER_ANALYTICS_SUCCESS";
export const LOAD_SELLER_ANALYTICS_FAIL = "LOAD_SELLER_ANALYTICS_FAIL";
export const LOGIN_MODAL = "LOGIN_MODAL";
